### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gom1n** [konai-kvl/TestWebPage#1]
### TODO
- [x] 카운팅 : Google Analytics를 쓸 지, 서버와 연동할 지는 팀원과 상의 -> **성훈M api 제작 및 연결**
- [x] 결과 > 절약 팁 > 한줄 텍스트 추가
- [x] 표지 화면 > 모나 로고 추가
- [x] 표지 화면 > 캐릭터 애니메이션 수정
- [x] 결과 > 결과 다운로드 이미지 연결
- [x] 결과 > 결과 공유하기 제목 이미지 연결
- [x] 질문 > 각 질문마다 이미지 연결

### 개발 요청 사항
- [x] 결과창 > 배경색 수정
- [x] 테스트 다시하기 버튼 클릭 시 index로 이동
